# -*- coding: utf-8 -*-
"""Loan_default_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYqIO1odaI5jjPtA8GMv7oZ_Y8PGPKwQ

# <center><b><b></center>

# <center><b>Loan Default Risk Analysis<b></center>


### 📌 **Problem Statement**
 Horizon Financial Group has experienced a significant increase in loan defaults across its personal lending portfolio during 2024–2025. With over 600 loans issued, the current default rate stands at approximately 25%, which is more than double the company’s target default rate of 12%. This rising trend poses a substantial risk to profitability, portfolio stability, and overall risk management practices. The objective of this analysis is to identify the key factors contributing to loan defaults by examining borrower characteristics (such as demographics, income, employment status, and credit score) alongside loan attributes (including loan amount, tenure, and interest rate). By leveraging these datasets, the analysis aims to uncover patterns, correlations, and high-risk segments within the loan portfolio. The insights derived from this study will support the VP of Risk in refining the company’s credit scoring model, improving underwriting criteria, and establishing more effective loan approval thresholds to reduce future default rates and enhance portfolio performance.

#### 📂**Import libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""#### 📁**Load Datasets**"""

!git clone https://github.com/muqadamfarheen/Loan-default-risk-analysis-.git

borrower = pd.read_csv("Loan-default-risk-analysis-/borrower_profiles.csv")

borrower.head()

loan = pd.read_csv("Loan-default-risk-analysis-/loan_applications.csv")

loan.head()

"""#### 🔍 **Data Overview**"""

borrower.info()

loan.info()

borrower.shape

"""#### 🔗 **Data Merging (Join Datasets)**"""

merged_df = pd.merge(borrower, loan, on="borrower_id", how="left")

merged_df.shape

"""#### 🔍 **Data Overview**"""

merged_df.head()

merged_df.info()

merged_df.drop_duplicates(inplace=True)

merged_df.shape
merged_df.info()

"""#### **Default Rate**"""

default_rate = merged_df["defaulted"].mean()
print(default_rate)

"""#### **24% Default Rate**

#### **Feature Engineering**
"""

bins = [520,600,650,700,750,850]

labels = [
"520-599",
"600-649",
"650-699",
"700-749",
"750+"
]

merged_df["credit_bucket"] = pd.cut(merged_df["credit_score"],
                             bins=bins,
                             labels=labels)

credit_default_rate = merged_df.groupby("credit_bucket")["defaulted"].mean()

credit_default_rate

credit_default_rate.plot(kind="bar")
plt.title("Credit Score vs Default Rate")
plt.xlabel("Credit Score")
plt.ylabel("Default Rate")
plt.show()

"""- borrowers below 600 credit score are showing high default rate"""

dti_bins = [0,20,30,40,50,70,100]

dti_labels = [
"0-20",
"20-30",
"30-40",
"40-50",
"50-70",
"70+"
]

merged_df["dti_bucket"] = pd.cut(merged_df["dti_ratio"],
                                 bins=dti_bins,
                                 labels=dti_labels)

dti_default_rate = merged_df.groupby("dti_bucket")["defaulted"].mean()
dti_default_rate

dti_default_rate.plot(kind="bar")
plt.title("DTI Ratio vs Default Rate")
plt.xlabel("DTI Ratio")
plt.ylabel("Default Rate")
plt.show()

"""- borrowers with dti ratio above 40% have high default rate"""

plt.scatter(merged_df["dti_ratio"], merged_df["defaulted"], alpha=0.5)
plt.title("DTI Ratio vs Default Rate")
plt.xlabel("DTI Ratio")
plt.ylabel("Default Rate")
plt.show()

"""- Raw scatter didn’t provide insight due to binary target. I aggregated default rate across DTI buckets to identify risk patterns, which is more meaningful for decision-making."""

purpose_default_rate = merged_df.groupby("loan_purpose")["defaulted"].mean()
purpose_default_rate

purpose_default_rate.sort_values().plot(kind="barh")
plt.title("Loan Purpose vs Default Rate")
plt.xlabel("Default Rate")
plt.ylabel("Loan Purpose")
plt.show()

"""- wedding , home improvement and auto loans are the top 3 categories with high default rate"""

merged_df.info()

employment_status_default_rate = merged_df.groupby("employment_status")["defaulted"].mean()
employment_status_default_rate

employment_status_default_rate.plot(kind="bar")
plt.title("Employment Status vs Default Rate")
plt.xlabel("Employment Status")
plt.ylabel("Default Rate")
plt.show

"""- Employment status is poor indicator for defautl rate hence passing it"""

merged_df.groupby("defaulted")["loan_amount"].mean()

sns.boxplot(x="defaulted", y="loan_amount", data=merged_df)
plt.title("Loan Amount vs Default Rate")
plt.xlabel("Default Rate")
plt.ylabel("Loan Amount")
plt.show

"""- high loan amount is showing slightly high default rate but not strong like credit score"""

merged_df['short_employment'] = merged_df['years_employed'] < 2

merged_df['short_employment'].value_counts()

employment_default = merged_df.groupby('short_employment')['defaulted'].mean()
employment_default

employment_default.plot(kind='bar')
plt.title('Short Employment vs Default Rate')
plt.xlabel('Short Employment')
plt.ylabel('Default Rate')
plt.show

"""- people with work experience less than 2 years have high default rate"""

corr = merged_df.corr(numeric_only = True)
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()



